name: Delay on automerging
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # This allows us to enable automerging, as the PR has to be in a non-mergable state before enabling it
      - name: Delay
        run: |
          sleep 15
