name: Generate ipynb files
on:
  push:
    branches: [ main ]
    paths:
    - 'philosophers'
    - 'hello_world'
    - 'micropython'
    - 'shell_module'
    - 'tensorflow_lite_micro'
    - 'template.py'
    - 'generate_demos.sh'
    - '.github/workflows/generate_ipynb_files.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GH_SERVICE_ACCOUNT_NAME: "renode-bot"
      GH_SERVICE_ACCOUNT_EMAIL: "renode-bot@antmicro.com"
      GH_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupytext
          pip install jinja-cli
          sudo apt install -y jq

      - name: Generate py demos
        run: |
          ./generate_demos.sh

      - name: Generate ipynb
        run: |
          cd boards
          find . -type f -name "*.py" -exec jupytext --update-metadata '{"kernelspec":{"name":"python3", "display_name":"Python 3"}}' --update --to ipynb {} \;
          cd ..

      - name: Configure git
        run: |
          git config --global user.name $GH_SERVICE_ACCOUNT_NAME
          git config --global user.email $GH_SERVICE_ACCOUNT_EMAIL

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-ipynb
          base: main
          delete-branch: true
          signoff: true
          committer: RenodeBot <renode-bot@antmicro.com>
          author: RenodeBot <renode-bot@antmicro.com>
          token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
          title: Generate ipynb files
          commit-message: Automatic update of ipynb files
          body: "Automatic update of ipynb files"

      # Sleep for a moment to enable automatic PR merging
      - name: Sleep
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        run: sleep 10

      - name: Enable automerge
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
          merge-method: rebase
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}

