name: Generate ipynb files
on:
  push:
    branches: [ testing ]
    paths:
    - 'test.py'
    - '.github/workflows/generate_ipynb_files.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GH_SERVICE_ACCOUNT_NAME: "renode-bot"
      GH_SERVICE_ACCOUNT_EMAIL: "renode-bot@antmicro.com"
      GH_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupytext

      - name: Generate test ipynb
        run: |
          jupytext --to ipynb test.py

      - name: Configure git
        run: |
          git config --global user.name $GH_SERVICE_ACCOUNT_NAME
          git config --global user.email $GH_SERVICE_ACCOUNT_EMAIL

      - name: GH CLI auth
        run: echo $GH_SERVICE_ACCOUNT_TOKEN | gh auth login --with-token

      - name: Commit and push
        if: github.event_name == 'push' && github.ref == 'refs/heads/testing'
        run: |
          export NEW_BRANCH=bot-$(date +%F_%H-%M)
          git checkout -b $NEW_BRANCH
          git add test.ipynb
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Generate ipynb files";
            git push -u https://$GH_SERVICE_ACCOUNT_NAME:$GH_SERVICE_ACCOUNT_TOKEN@github.com/antmicro/test-colabs.git $NEW_BRANCH
            gh pr create --fill --head $NEW_BRANCH --base testing
            gh pr merge --auto --rebase --delete-branch
          else
            echo "no changes";
          fi
